[package]
name = "leson2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slug="0.1.4"
base64="0.21.4"
sha256="1.4.0"